### ISSUE TITLE
Update README to include Installation Guide

### ISSUE THREAD

**Issue by dennohpeter** [yash3001/qtile#1]
It would be great if you added an installation  guide to have this up and running @yash3001 @test-gamma

**Comment by yash3001** [comment]
Yes i will be adding the guide in the future. Currently i have exams so not possible till 30th July.

**Comment by dennohpeter** [comment]
okay, I understand.

**Comment by dennohpeter** [comment]
but I've a quick question, I just clone the repo as

git clone --depth 1 https://github.com/yash3001/qtile.git 

should I cd into qtile and execute autostart.sh file  or I how should do it in the meantime?

**Comment by yash3001** [comment]
> should I cd into qtile and execute autostart.sh file or I how should do it in the meantime?

autostart.sh will run by itself when qtile is started
